### ISSUE TITLE
no such file /ledgerfiles/assets-dkb.ledger

### ISSUE THREAD

**Issue by hummuscience** [leoc/ledgit#4]
I am trying to use it to get my transactions from DKB and hitting the following error:

```
Traceback (most recent call last):
	12: from /Users/muadabdelhay/.ledgit/bin/ledgit:22:in `<main>'
	11: from /Users/muadabdelhay/.ledgit/lib/ledgit.rb:19:in `run'
	10: from /Users/muadabdelhay/.ledgit/lib/ledgit.rb:19:in `each'
	 9: from /Users/muadabdelhay/.ledgit/lib/ledgit.rb:20:in `block in run'
	 8: from /Users/muadabdelhay/.ledgit/lib/handler.rb:101:in `get'
	 7: from /Users/muadabdelhay/.ledgit/lib/handler.rb:101:in `new'
	 6: from /Users/muadabdelhay/.ledgit/lib/handler.rb:9:in `initialize'
	 5: from /Users/muadabdelhay/.ledgit/lib/handler.rb:9:in `new'
	 4: from /Users/muadabdelhay/.ledgit/lib/ledgit/ledger_file.rb:11:in `initialize'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1127:in `touch'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1127:in `each'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1130:in `block in touch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1130:in `utime': No such file or directory @ apply2files - /ledgerfiles/assets-dkb.ledger (Errno::ENOENT)
	14: from /Users/muadabdelhay/.ledgit/bin/ledgit:22:in `<main>'
	13: from /Users/muadabdelhay/.ledgit/lib/ledgit.rb:19:in `run'
	12: from /Users/muadabdelhay/.ledgit/lib/ledgit.rb:19:in `each'
	11: from /Users/muadabdelhay/.ledgit/lib/ledgit.rb:20:in `block in run'
	10: from /Users/muadabdelhay/.ledgit/lib/handler.rb:101:in `get'
	 9: from /Users/muadabdelhay/.ledgit/lib/handler.rb:101:in `new'
	 8: from /Users/muadabdelhay/.ledgit/lib/handler.rb:9:in `initialize'
	 7: from /Users/muadabdelhay/.ledgit/lib/handler.rb:9:in `new'
	 6: from /Users/muadabdelhay/.ledgit/lib/ledgit/ledger_file.rb:11:in `initialize'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1127:in `touch'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1127:in `each'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1129:in `block in touch'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1133:in `rescue in block in touch'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1133:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1133:in `initialize': No such file or directory @ rb_sysopen - /ledgerfiles/assets-dkb.ledger (Errno::ENOENT)
```

I realize I need to create the ledgerfile but I am have no clue where... I tried putting it in my home directory, the .ledgit directory, but none worked

**Comment by leoc** [comment]
Hi there!

Please have a look at the `https://github.com/leoc/ledgit/blob/master/ledgit.json.example`.
Via this file you configure your handlers and file paths.

Currently the handlers are broken though. DKB as other german online banking accounts began requiring TANs or 2FA to log in. This is not automatable as of now.
